inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/*_helper.rb'

Metrics/LineLength:
  Exclude:
    - '*file'
    - 'config/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'config/routes.rb'
